<?php

return [
    'api_key' => env('RAJAONGKIR_API_KEY', ''),
    'base_url' => env('RAJAONGKIR_BASE_URL', 'https://api.rajaongkir.com/starter'),
    'origin_city_id' => env('RAJAONGKIR_ORIGIN_CITY_ID', 23), // 23 = Kota Bandung

    'couriers' => [
        'jne' => 'JNE',
        'jnt' => 'J&T',
        'sicepat' => 'SiCepat',
        'pos' => 'POS Indonesia',
        'tiki' => 'TIKI',
    ],

    'city_ids' => [
        'Bandung' => 23,
        'Kota Bandung' => 23,
        'Cimahi' => 29,
        'Jakarta' => 152,
        'Jakarta Pusat' => 152,
        'Jakarta Selatan' => 153,
        'Jakarta Barat' => 151,
        'Jakarta Timur' => 155,
        'Jakarta Utara' => 154,
        'Bogor' => 218,
        'Kota Bogor' => 218,
        'Depok' => 327,
        'Kota Depok' => 327,
        'Tangerang' => 459,
        'Kota Tangerang' => 459,
        'Bekasi' => 386,
        'Kota Bekasi' => 386,
        'Surabaya' => 444,
        'Kota Surabaya' => 444,
        'Yogyakarta' => 501,
        'Kota Yogyakarta' => 501,
        'Semarang' => 422,
        'Kota Semarang' => 422,
        'Medan' => 131,
        'Kota Medan' => 131,
        'Makassar' => 450,
        'Kota Makassar' => 450,
        'Palembang' => 374,
        'Kota Palembang' => 374,
        'Malang' => 301,
        'Kota Malang' => 301,
        'Denpasar' => 114,
        'Kota Denpasar' => 114,
        'Balikpapan' => 160,
        'Kota Balikpapan' => 160,
        'Samarinda' => 426,
        'Kota Samarinda' => 426,
        'Banjarmasin' => 157,
        'Kota Banjarmasin' => 157,
        'Pekanbaru' => 375,
        'Kota Pekanbaru' => 375,
        'Batam' => 255,
        'Kota Batam' => 255,
        'Padang' => 367,
        'Kota Padang' => 367,
        'Pontianak' => 387,
        'Kota Pontianak' => 387,
        'Manado' => 302,
        'Kota Manado' => 302,
        'Mataram' => 306,
        'Kota Mataram' => 306,
        'Kupang' => 296,
        'Kota Kupang' => 296,
        'Ambon' => 360,
        'Kota Ambon' => 360,
        'Jayapura' => 361,
        'Kota Jayapura' => 361,
        'Solo' => 449,
        'Kota Surakarta' => 449,
    ],

    'fallback_rates' => [
        'jne' => [
            ['service' => 'OKE', 'description' => 'Ongkos Kirim Ekonomis', 'cost' => 12000, 'etd' => '3-5'],
            ['service' => 'REG', 'description' => 'Layanan Reguler', 'cost' => 15000, 'etd' => '2-3'],
            ['service' => 'YES', 'description' => 'Yakin Esok Sampai', 'cost' => 25000, 'etd' => '1'],
        ],
        'jnt' => [
            ['service' => 'ECO', 'description' => 'Economy', 'cost' => 10000, 'etd' => '3-6'],
            ['service' => 'REG', 'description' => 'Reguler', 'cost' => 14000, 'etd' => '2-3'],
            ['service' => 'EZ', 'description' => 'EZ (Same Day)', 'cost' => 28000, 'etd' => '1'],
        ],
        'sicepat' => [
            ['service' => 'REG', 'description' => 'Reguler', 'cost' => 15000, 'etd' => '2-4'],
            ['service' => 'SIUNT', 'description' => 'Untung (Ekonomis)', 'cost' => 10000, 'etd' => '4-7'],
            ['service' => 'BEST', 'description' => 'Besok Sampai', 'cost' => 24000, 'etd' => '1'],
        ],
        'pos' => [
            ['service' => 'Paket Kilat Khusus', 'description' => 'Paket Kilat Khusus', 'cost' => 11000, 'etd' => '3-7'],
        ],
        'tiki' => [
            ['service' => 'ONS', 'description' => 'Over Night Service', 'cost' => 22000, 'etd' => '1'],
            ['service' => 'REG', 'description' => 'Reguler', 'cost' => 13000, 'etd' => '2-4'],
        ],
    ],
];
